[package]
name = "vampire-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
vampire = { path = "../vampire" }
tokio = { version = "1.47.1", features = ["full"] }