[package]
name = "vampire"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = { workspace = true }
libc = "0.2"
libloading = "0.8"
inventory = "0.3"
vampire-macro = { path = "../vampire-macro" }